name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [master]

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Service Fellowship AI Code Reviewer
        uses: pomier/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4o"
          exclude: "**/*.json"
          bot_name: Service Fellowship
